version: "3"

services:
  user_service:
    build: user_service
    ports:
      - "8001:8000"
    volumes:
      - ./user_service:/app
    environment:
      - SECRET_KEY=your-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn user_service:app --host 0.0.0.0 --port 8000 --reload
  delivery_service:
    build: delivery_service
    ports:
      - "8002:8000"
    volumes:
      - ./delivery_service:/app
    environment:
      - SECRET_KEY=your-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - user_service
    command: uvicorn delivery_service:app --host 0.0.0.0 --port 8000 --reload